# Generated by Django 3.2.6 on 2021-10-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('costumer_name', models.CharField(blank=True, max_length=50)),
                ('costumer_mobile', models.CharField(max_length=50)),
                ('costumer_adress', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
