# Generated by Django 3.2.6 on 2021-10-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211021_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_quantity', models.FloatField(default=0)),
                ('sale_quantity', models.FloatField(default=0)),
                ('total_balance_quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('purcharse', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.purchase')),
                ('sale', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.sale')),
            ],
        ),
    ]
